"""add hierarchical project structure with gps location mapping

Revision ID: 5fd743e1ba9f
Revises: 
Create Date: 2026-02-04 14:42:40.515035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fd743e1ba9f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('corridor_name', sa.String(length=255), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=True),
    sa.Column('start_lng', sa.Float(), nullable=True),
    sa.Column('end_lat', sa.Float(), nullable=True),
    sa.Column('end_lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_project_id'), 'packages', ['project_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('segment_name', sa.String(length=255), nullable=False),
    sa.Column('chainage_start_km', sa.Float(), nullable=True),
    sa.Column('chainage_end_km', sa.Float(), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=False),
    sa.Column('start_lng', sa.Float(), nullable=False),
    sa.Column('end_lat', sa.Float(), nullable=False),
    sa.Column('end_lng', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_package_id'), 'locations', ['package_id'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_path', sa.String(length=512), nullable=False),
    sa.Column('processed_video_path', sa.String(length=512), nullable=True),
    sa.Column('json_file_path', sa.String(length=512), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('detection_type', sa.String(length=50), nullable=False),
    sa.Column('speed_kmh', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_location_id'), 'videos', ['location_id'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('package_id', sa.String(length=36), nullable=True),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detection_type', sa.String(length=50), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('bounding_box', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_video_frame', 'detections', ['video_id', 'frame_number'], unique=False)
    op.create_index(op.f('ix_detections_frame_number'), 'detections', ['frame_number'], unique=False)
    op.create_index(op.f('ix_detections_location_id'), 'detections', ['location_id'], unique=False)
    op.create_index(op.f('ix_detections_package_id'), 'detections', ['package_id'], unique=False)
    op.create_index(op.f('ix_detections_project_id'), 'detections', ['project_id'], unique=False)
    op.create_index(op.f('ix_detections_video_id'), 'detections', ['video_id'], unique=False)
    op.create_table('processing_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'ERROR', name='processingstatusenum'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_frame', sa.Integer(), nullable=True),
    sa.Column('total_frames', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_status_video_id'), 'processing_status', ['video_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_status_video_id'), table_name='processing_status')
    op.drop_table('processing_status')
    op.drop_index(op.f('ix_detections_video_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_project_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_package_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_location_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_frame_number'), table_name='detections')
    op.drop_index('idx_video_frame', table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_videos_location_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_locations_package_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_packages_project_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_table('projects')
    # ### end Alembic commands ###
